-- API 연결 이름 중복 방지 유니크 제약 (#647)
--
-- api_connection.name 컬럼에는 애초에 유니크 제약이 없어(V93 마이그레이션 주석 참고) 동일 테넌트
-- 안에서 같은 이름의 연결이 여러 개 만들어질 수 있었다. 목록/삭제 확인 다이얼로그가 이름만으로
-- 항목을 구분해, 이름이 겹치면 사용자가 다른 연결을 실수로 삭제할 위험이 있었다.
--
-- 애플리케이션 레벨 검증(ApiConnectionService.validateNameNotDuplicated)을 먼저 추가했고, 이
-- 마이그레이션은 DB 레벨에서도 동일 규칙을 강제해 경합 상황(TOCTOU)에서도 중복이 생기지 않도록
-- 방어한다. 적용 전 로컬/개발 DB를 직접 조회해 (tenant_id, name) 기준 중복이 없음을 확인했다
-- (2026-09-11). pipeline.name 이 이미 동일 패턴(V93)으로 (tenant_id, name) 유니크 인덱스를
-- 쓰고 있어 그 관행을 그대로 따른다.
--
-- 주의: 이 마이그레이션을 중복 데이터가 있는 환경(예: 별도로 방치된 운영 DB)에 적용하면 제약
-- 위반으로 실패한다 — 그 경우 먼저 중복 레코드를 사람이 검토해 정리한 뒤 재시도해야 한다(자동
-- 접미사 부여 등으로 실 데이터를 임의로 바꾸지 않는다).
CREATE UNIQUE INDEX idx_api_connection_tenant_name ON api_connection(tenant_id, name);
