-- V48: 차트 타입 9종 추가 (HISTOGRAM/BOXPLOT/HEATMAP/TREEMAP/FUNNEL/RADAR/WATERFALL/GAUGE/CANDLESTICK)
ALTER TABLE chart DROP CONSTRAINT IF EXISTS chart_chart_type_check;
ALTER TABLE chart ADD CONSTRAINT chart_chart_type_check
    CHECK (chart_type IN (
        'BAR', 'LINE', 'PIE', 'AREA', 'SCATTER', 'DONUT', 'TABLE', 'MAP',
        'HISTOGRAM', 'BOXPLOT', 'HEATMAP', 'TREEMAP', 'FUNNEL', 'RADAR',
        'WATERFALL', 'GAUGE', 'CANDLESTICK'
    ));
