-- 온톨로지 DB 승격 (B-2a): ai-agent 정적 CORE_ONTOLOGY 를 단일 소유 테이블로 이관한다.
-- 단일 온톨로지 전제. schema_version 은 B-2a 에선 1 고정, 편집(B-2b) 시 증가.
CREATE TABLE IF NOT EXISTS ontology (
    id             BIGINT       PRIMARY KEY,
    domain         TEXT         NOT NULL,
    schema_version INT          NOT NULL DEFAULT 1,
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- 엔티티 타입. resolution 은 embedding|exact 만 허용. sort_order 로 프롬프트 조립 순서(바이트 동일성) 보존.
CREATE TABLE IF NOT EXISTS ontology_entity_type (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ontology_id BIGINT      NOT NULL REFERENCES ontology(id) ON DELETE CASCADE,
    type        TEXT        NOT NULL,
    description TEXT        NOT NULL,
    naming      TEXT        NOT NULL,
    resolution  TEXT        NOT NULL CHECK (resolution IN ('embedding','exact')),
    sort_order  INT         NOT NULL,
    UNIQUE (ontology_id, type)
);

-- 관계(허용 트리플). sort_order 로 순서 보존.
CREATE TABLE IF NOT EXISTS ontology_relation (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ontology_id BIGINT      NOT NULL REFERENCES ontology(id) ON DELETE CASCADE,
    subject     TEXT        NOT NULL,
    relation    TEXT        NOT NULL,
    object      TEXT        NOT NULL,
    description TEXT        NOT NULL,
    sort_order  INT         NOT NULL
);

-- 시드: CORE_ONTOLOGY 원본을 배열 순서 그대로 삽입(문자열 정확 보존).
INSERT INTO ontology (id, domain, schema_version) VALUES (1, '화재조사 보고서', 1);

INSERT INTO ontology_entity_type (ontology_id, type, description, naming, resolution, sort_order) VALUES
  (1, 'Incident',   '사건/이벤트 (예: 발생한 화재)', '문서마다 고유해야 한다. 핵심 식별 속성(장소·일자 등)을 포함해 구성하고, 일반명이나 문서 번호를 이름으로 쓰지 마라. 한 문서에서 정확히 1개만 추출한다.', 'exact',     0),
  (1, 'Building',   '물리적 장소/건물',              '본문에 등장한 표기를 그대로 사용한다.', 'embedding', 1),
  (1, 'Cause',      '발화·발생 원인',                '본문에 등장한 표기를 그대로 사용한다.', 'embedding', 2),
  (1, 'Damage',     '피해 내역',                     '본문에 등장한 표기를 그대로 사용한다.', 'exact',     3),
  (1, 'Equipment',  '소방 설비/장비',                '본문에 등장한 표기를 그대로 사용한다.', 'embedding', 4),
  (1, 'Regulation', '관련 법규/기준',                '본문에 등장한 표기를 그대로 사용한다.', 'embedding', 5);

INSERT INTO ontology_relation (ontology_id, subject, relation, object, description, sort_order) VALUES
  (1, 'Incident',  'OCCURRED_AT',   'Building',    '사건이 발생한 장소',      0),
  (1, 'Incident',  'CAUSED_BY',     'Cause',       '사건의 발화·발생 원인',   1),
  (1, 'Incident',  'RESULTED_IN',   'Damage',      '사건이 초래한 피해',      2),
  (1, 'Building',  'HAS_EQUIPMENT', 'Equipment',   '건물이 보유한 설비',      3),
  (1, 'Incident',  'VIOLATED',      'Regulation',  '사건에서 위반된 규정',    4),
  (1, 'Equipment', 'GOVERNED_BY',   'Regulation',  '설비를 규율하는 규정',    5);
