-- 엔티티 데이터 프로퍼티(수치/날짜/텍스트 속성). 엔티티 타입 1:N.
-- data_type 은 text|number|date 만 허용. sort_order 로 프롬프트 조립 순서 안정화.
-- unit 은 number 정규화 목표 단위(예: '원') — 없으면 NULL.
CREATE TABLE IF NOT EXISTS ontology_entity_property (
    id             BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type_id BIGINT      NOT NULL REFERENCES ontology_entity_type(id) ON DELETE CASCADE,
    name           TEXT        NOT NULL,
    description    TEXT        NOT NULL,
    data_type      TEXT        NOT NULL CHECK (data_type IN ('text','number','date')),
    unit           TEXT,
    sort_order     INT         NOT NULL,
    UNIQUE (entity_type_id, name)
);

-- 시드: 첫 사례로 Incident 에 '피해액'(number, 원). 추출 프롬프트가 description 을 정규화 지침으로 사용.
INSERT INTO ontology_entity_property (entity_type_id, name, description, data_type, unit, sort_order)
SELECT et.id, '피해액',
       '화재로 인한 재산 피해 총액을 원 단위 정수로 추출. ''억''=1e8, ''만''=1e4 로 환산하고 콤마·통화기호 제거. 범위·근사값은 대표값 1개만.',
       'number', '원', 0
FROM ontology_entity_type et
JOIN ontology o ON o.id = et.ontology_id
WHERE o.id = 1 AND et.type = 'Incident'
ON CONFLICT (entity_type_id, name) DO NOTHING;
