-- 다중 온톨로지 기반(슬라이스 0): 싱글톤(id=1) 제약을 풀어 도메인별 온톨로지를 여러 개 허용하고,
-- 데이터셋↔온톨로지 N:1 바인딩을 명시적 레코드로 저장한다. ai-agent/Neo4j 무변경.

-- ① 도메인당 온톨로지 1개 보장(조회 안정성). 기존 시드 1행('화재조사 보고서')뿐이라 충돌 없음.
ALTER TABLE ontology ADD CONSTRAINT ontology_domain_unique UNIQUE (domain);

-- ② 신규 온톨로지 INSERT 시 id 자동 발급. 기존 id=1은 명시 INSERT였으므로 보존하고,
--    시퀀스를 2부터 시작해 충돌을 피한다(BY DEFAULT: 명시 id도 계속 허용).
ALTER TABLE ontology ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 2);

-- ③ 데이터셋↔온톨로지 바인딩. 데이터셋당 1개(UNIQUE) = N:1. 별도 테이블(코어 dataset 무변경,
--    dataset_graph_ingest 분리 패턴과 일치). dataset_id는 audit 패턴대로 FK 없이 BIGINT.
CREATE TABLE IF NOT EXISTS dataset_ontology (
    dataset_id  BIGINT      NOT NULL UNIQUE,
    ontology_id BIGINT      NOT NULL REFERENCES ontology(id) ON DELETE CASCADE,
    bound_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    bound_by    BIGINT
);

-- 온톨로지별 바인딩 데이터셋 역조회용 인덱스.
CREATE INDEX IF NOT EXISTS idx_dataset_ontology_ontology ON dataset_ontology (ontology_id);
